export default {
  LOAD_TO_END: 'TASKS_LOAD_TO_END',
  LOAD: 'TASKS_LOAD',
  SET_FILTER: 'SET_FILTER',
  TASKS_FILTER_PROGRESS: 'TASKS_FILTER_PROGRESS',
  TASKS_FILTER_ERROR: 'TASKS_FILTER_ERROR',
  TASKS_FILTER_CLEAR: 'TASKS_FILTER_CLEAR',
  TASK_CHANGE_SUCCESS: 'TASK_CHANGE_SUCCESS',
  TASK_CHANGE_ERROR: 'TASK_CHANGE_ERROR',
  TASK_CHANGE_CLEAR: 'TASK_CHANGE_CLEAR',
  TASK_REMOVE_SUCCESS: 'TASK_REMOVE_SUCCESS',
  TASK_REMOVE_ERROR: 'TASK_REMOVE_ERROR',
  TASK_REMOVE_CLEAR: 'TASK_REMOVE_CLEAR',
  TASK_ADD_SUCCESS: 'TASK_ADD_SUCCESS',
  TASK_ADD_ERROR: 'TASK_ADD_ERROR',
  TASK_ADD_CLEAR: 'TASK_ADD_CLEAR'
}